.ai-review-base:
  when: manual
  image: nikitafilonov/ai-review:latest
  stage: checks
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
  script:
    - ai-review run
  variables:
    # LLM
    LLM.PROVIDER: "OPENAI"
    LLM.META.MODEL: "gpt-4o-mini"
    LLM.META.MAX_TOKENS: "1200"
    LLM.META.TEMPERATURE: "0.3"
    LLM.HTTP_CLIENT.API_URL: "https://api.openai.com/v1"

    # VCS
    VCS.PROVIDER: "GITLAB"
    VCS.HTTP_CLIENT.API_URL: "$CI_SERVER_URL"
    VCS.HTTP_CLIENT.API_TOKEN: "$CI_JOB_TOKEN"
    VCS.PIPELINE.PROJECT_ID: "$CI_PROJECT_ID"
    VCS.PIPELINE.MERGE_REQUEST_ID: "$CI_MERGE_REQUEST_IID"

    # Prompts
    PROMPT.INLINE_PROMPT_FILE: "./prompts/inline.md"
    PROMPT.SUMMARY_PROMPT_FILE: "./prompts/summary.md"

    # Review
    REVIEW.MODE: "CHANGED_WITH_CONTEXT"
    REVIEW.CONTEXT_LINES: "10"
    REVIEW.REVIEW_CHANGE_MARKER: "# changed"
  allow_failure: true

.ai-review-inline:
  script:
    - ai-review run-inline
  extends: .ai-review-base

.ai-review-summary:
  script:
    - ai-review run-summary
  extends: .ai-review-base
