name: Lint and Test

on:
  push:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install ruff
      - run: ruff check ai_review

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      AI_REVIEW_CONFIG_FILE_YAML: "./ai_review/tests/configs/config-test.yaml"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install .[test] pytest pytest-cov
      - run: pytest --cov=ai_review --cov-report=xml --cov-report=term-missing
