name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image-name: ghcr.io/neilontrue/ai-review:latest