name: 🤖 Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  lint:
    name: 🧹 lint
    uses: ./.github/workflows/reusable-lint.yml

  test:
    name: 🧪 test
    uses: ./.github/workflows/reusable-test.yml
    needs: lint

  review:
    name: 🤖 review
    uses: ./.github/workflows/reusable-review.yml
    needs: test