name: 🤖 AI Code Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: lint

  review:
    uses: ./.github/workflows/reusable-review.yml
    needs: test